# Generated by Django 5.2.7 on 2025-10-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningblockmodel',
            old_name='content',
            new_name='contents',
        ),
    ]
